name: Go Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Go app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17  # Adjust this to your preferred Go version

    - name: Build
      run: go build

    - name: Check Auto
      run: |
        export GOPATH=`go env GOPATH` &&
        export PATH="$GOPATH/bin:$PATH" &&
        go install github.com/relaxnow/vcgopkg
        ls -la */**
        pwd
    
    
